### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by mszarlinski** [spring-petclinic/spring-petclinic-microservices#1]
README file has been copied from AngularJS branch and must be updated.

**Comment by arey** [comment]
Yes, I would like to know how to start all those services?
Maybe with Docker or Spring Cloud CLI? https://cloud.spring.io/spring-cloud-cli/

**Comment by mszarlinski** [comment]
I don't have experience with Spring Cloud CLI as of yet, so I've created yesterday a task #2 for Docker. If anyone can provide a Spring Cloud CLI setup, we probably could use it instead of Docker.

**Comment by arey** [comment]
AngularJS documentation has been updated into the https://github.com/spring-petclinic/spring-petclinic-microservices/pull/29

**Comment by arey** [comment]
I propose to complete the readme.md with some database information then remove petclinic_db_setup_mysql.txt and db_readme.txt files

**Comment by arey** [comment]
With PR #33 the Front-end module table has to be updated.

**Comment by arey** [comment]
@mszarlinski could we close this issue?
