### ISSUE TITLE
Update to JDK11 (or 10)

### ISSUE THREAD

**Issue by notsureifkevin** [spring-petclinic/spring-petclinic-microservices#102]
I've been working on an opentracing workshop for OSS Summit EU and this is the microservice project I landed on when decided what I should instrument.

I have managed to upgrade to JDK10 (it'll be 11 once bionic beaver updates their jdk11 packages to actually deliver 11 instead of 10). I've also done some other enhancements which you might be interested in. (see other issues).

There is a caveat though, the docker plugin still works but it hangs for a few seconds before throwing an error about authentication. Since you're not pushing images from maven (from what I can tell) I assumed this wasn't a blocker for my use case. I'm guessing that a module is missing but I didn't debug or attempt to fix.

**Comment by arey** [comment]
I'm agree to support the JDK 11 and, potentially upgrade the Docker images. But I prefer to keep a compatibility with Java 8 that remains the most established platform version.

For JDK 11 support, maybe we have to upgrade to Spring Boot 2.1 and Spring Framework 5.1. There is Java 11 initial support. See:
- https://github.com/spring-projects/spring-framework/wiki/What's-New-in-Spring-Framework-5.x
- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1.0-M2-Release-Notes

**Comment by kcrawley** [comment]
Ok, that makes sense. We can always circle back to this when 11 support is a bit more flushed out.

**Comment by arey** [comment]
I propose to create a `release/java11`branch. See https://github.com/spring-petclinic/spring-petclinic-microservices/pull/130
