### ISSUE TITLE
docker-compose for Mysql DB

### ISSUE THREAD

**Issue by nidhi-parmar** [spring-petclinic/spring-petclinic-microservices#116]
not able to understand docker-compose for Mysql db...

**Comment by arey** [comment]
@nidhi-parmar  are you interesting by adding this feature?

**Comment by tscrypter** [comment]
I'll take a stab at this.

**Comment by arey** [comment]
Thanks @tscrypter. Could you work on it then submit a Pull Request?

**Comment by tscrypter** [comment]
I'll be doing that tonight.

**Comment by arey** [comment]
Please reopen if needed
