### ISSUE TITLE
Replace Hystrix, Hystrix Dashboard, Ribon and Zuul

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-microservices#117]
According to the blog post titled `Spring Cloud Greenwich.RC1 available now` 
 https://spring.io/blog/2018/12/12/spring-cloud-greenwich-rc1-available-now, some Spring Cloud Netflix modules will be placed into maintenance mode.

Pivotal recommend the following as replacements for the functionality provided by these module:

CURRENT | REPLACEMENT
-- | --
Hystrix | Resilience4j
Hystrix Dashboard / Turbine | Micrometer + Monitoring System
Ribbon | Spring Cloud Loadbalancer
Zuul 1 | Spring Cloud Gateway
Archaius 1 | Spring Boot external config + Spring Cloud Config

Pivotal intends to continue to support these modules for a period of at least a year from the general availability of the Greenwich release train.

Spring Cloud Circuit Breaker is a new project we could use to migrate from Hystrix to Resilience4J or Sentinel : https://www.infoq.com/news/2019/05/spring-cloud-pluggable-circuit

Another interesting article from the Netflix Techblog: https://medium.com/netflix-techblog/netflix-oss-and-spring-boot-coming-full-circle-4855947713a0

Spring Cloud Greenwich.RELEASE is now available: https://spring.io/blog/2019/01/23/spring-cloud-greenwich-release-is-now-available

**Comment by arey** [comment]
Ribbon, Zuul 1, Hystrix and Hystrix dashboard have been replaced.

**Comment by kchvilyov** [comment]
Thank you for good example @arey .
Is it possible to replace only Hystrix by Resilience4j
but not replace the others? :
2.Hystrix Dashboard / Turbine by Micrometer + Monitoring System
3. Ribbon by Spring Cloud Loadbalancer
4. Zuul by Spring Cloud Gateway
5.Archaius by Spring Boot external config + Spring Cloud Config

**Comment by arey** [comment]
You could fork the repo, checkout an older version and apply the commit https://github.com/spring-petclinic/spring-petclinic-microservices/commit/b501fdb20a764e7b4c64ec32befeaada797ebc89

**Comment by kchvilyov** [comment]
Sorry, @arey .
I use this project as beautiful example only. I am not going to change your project.
I work on replace Hystrix by Resilience4j in another our internal corporate microservice project. 
Your answer can help me to select and estimate optimal way and time for replace Hystrix by Resilience4j for the internal corporate project.

**Comment by kchvilyov** [comment]
> You could fork the repo, checkout an older version and apply the commit [b501fdb](https://github.com/spring-petclinic/spring-petclinic-microservices/commit/b501fdb20a764e7b4c64ec32befeaada797ebc89)

**Thank you @arey .
I see you added commits "Migrate from Netflix Zuul to Spring Cloud Gateway" before this commit.
Was it necessary to "Migrate from Netflix Zuul" before "Replace Hystrix by Spring Cloud Circuit Breaker and Resilience4j"?**

arey added a commit to arey/spring-petclinic-microservices that referenced this issue on 9 Apr 2019
@arey
Migrate from Netflix Zuul to Spring Cloud Gateway spring-petclinic#117
2c739b9
arey added a commit to arey/spring-petclinic-microservices that referenced this issue on 8 May 2019
@arey
Netflix Zuul replaced by Spring Cloud Gateway spring-petclinic#117
497e1d3
arey added a commit that referenced this issue on 29 Aug 2019
@arey
Merge pull request #125 from arey/feature/spring-cloud-gateway …
2d63942

**Comment by arey** [comment]
Zuul and Hystrix are part of the Netflix OSS. Zuul creates a Hystrix circuit breaker for each route. I don't know if Zuul supports Resilience4j. But I don't think so.
