### ISSUE TITLE
Fail-over support

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-microservices#12]
When I start 2 instances of ClientsServiceApplication on my desktop then I stop the first started one, the second instance is not seen by Eureka and the app does not work. Any idea?

**Comment by mszarlinski** [comment]
It looks like default Eureka settings don't allow to register multiple instances of the same application with `server.port=0`. I am preparing a fix for that and learning a new thing :).

**Comment by arey** [comment]
I'm learning too.
@mszarlinski I don't see your commit. Do you have push it?

**Comment by mszarlinski** [comment]
Commit was merged to config repo, no changes needed here. You can see a pull request: https://github.com/spring-petclinic/spring-petclinic-microservices-config/pull/1

**Comment by arey** [comment]
Ok thanks
