### ISSUE TITLE
JDK 10 Maven Build Error

### ISSUE THREAD

**Issue by pwittrock** [spring-petclinic/spring-petclinic-microservices#129]
Building with Java 10 results in an error.  Looks like this issue: https://github.com/spring-projects/spring-petclinic/issues/349

**Comment by arey** [comment]
I've got this error:
```
[ERROR] Failed to execute goal ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run (default) on project spring-petclinic-api-gateway: Execution default of goal ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run failed: An API incompatibility was encountered while executing ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>ro.isdc.wro4j:wro4j-maven-plugin:1.8.0
```
The `wro4j-maven-plugin` is not compatible with Java 9,10 and 11 and seems to be not supported: https://github.com/wro4j/wro4j/issues/1039

**Comment by arey** [comment]
Next week, I will work on a Java 11 version (probably in a separate branch)

**Comment by arey** [comment]
It should be OK. I let you test.
