### ISSUE TITLE
spring-petclinic-microservices unable to build docker image

### ISSUE THREAD

**Issue by anandrece** [spring-petclinic/spring-petclinic-microservices#135]
I am trying to build docker images with the below Dockerfile. 

FROM openjdk:8-jre-alpine
VOLUME /tmp
ARG DOCKERIZE_VERSION=v0.6.1
ARG ARTIFACT_NAME
ARG EXPOSED_PORT
ENV SPRING_PROFILES_ACTIVE docker
ADD https://github.com/jwilder/dockerize/releases/download/${DOCKERIZE_VERSION}/dockerize-alpine-linux-amd64-${DOCKERIZE_VERSION}.tar.gz dockerize.tar.gz
RUN tar xzf dockerize.tar.gz
RUN chmod +x dockerize
ADD ${ARTIFACT_NAME}.jar /app.jar
RUN touch /app.jar
EXPOSE ${EXPOSED_PORT}
ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

but the arguments ARTIFACT_NAME  and EXPOSED_PORT is not taking automatically during build. I have pasted the errors below,

Sending build context to Docker daemon  402.7MB
Step 1/13 : FROM openjdk:8-jre-alpine
 ---> f7a292bbb70c
Step 2/13 : VOLUME /tmp
 ---> Using cache
 ---> 482a505d3477
Step 3/13 : ARG DOCKERIZE_VERSION=v0.6.1
 ---> Using cache
 ---> e3e43f6bca14
Step 4/13 : ARG ARTIFACT_NAME
 ---> Using cache
 ---> 2ffe4176d521
Step 5/13 : ARG EXPOSED_PORT
 ---> Using cache
 ---> 243803c2def1
Step 6/13 : ENV SPRING_PROFILES_ACTIVE docker
 ---> Using cache
 ---> ad74d4ca0020
Step 7/13 : ADD https://github.com/jwilder/dockerize/releases/download/${DOCKERIZE_VERSION}/dockerize-alpine-linux-amd64-${DOCKERIZE_VERSION}.tar.gz dockerize.tar.gz
Downloading [==================================================>]  3.006MB/3.006MB
 ---> Using cache
 ---> 6d111d95bbc0
Step 8/13 : RUN tar xzf dockerize.tar.gz
 ---> Using cache
 ---> 061f6a7c4260
Step 9/13 : RUN chmod +x dockerize
 ---> Using cache
 ---> b9c7f21ba302
Step 10/13 : ADD ${ARTIFACT_NAME}.jar /app.jar
ADD failed: stat /var/lib/docker/tmp/docker-builder734454922/.jar: no such file or directory

Please help me on this issue.

**Comment by arey** [comment]
I think the mistake could come from the missing `ARTIFACT_NAME` parameter. I see the .jar exension without filename : `stat /var/lib/docker/tmp/docker-builder734454922/.jar:`

**Comment by arey** [comment]
Please reopen this issue if needed
