### ISSUE TITLE
 Service discovery behavior with Kubernetes

### ISSUE THREAD

**Issue by sindhams** [spring-petclinic/spring-petclinic-microservices#138]
I deployed the petclinic application on kubernetes but the service discovery is happening with pod names, but it should happen with kubernetes service names. how do we achieve this

**Comment by arey** [comment]
Hi @sindhams I've never try to deploy the application on kubernetes but I hope someone could help you.

**Comment by tscrypter** [comment]
@sindhams @arey Running this on K8s requires some code and architecture changes. Service Discovery is a feature provided OOTB by K8s.

### Architecture change:
1. K8s provides its own service discovery, so `spring-cloud-discovery-server` won't be deployed.

### Code changes:
1. Replace `spring-cloud-starter-netflix-eureka-client` with Spring Cloud Kubernetes DiscoveryClient (this is throughout most of the services)
2. Fix any issues that arise from the first change (I haven't had a chance to do this on this repo, but for my services in K8s I have services communicating with each other and monitored via SBA using the native Service Discovery)

I can probably take a stab and creating a PR next week for a new branch in this repo with the updates made to support deployment on K8s, as well as documentation for running a development cluster locally.

**Comment by tscrypter** [comment]
An additional thought, less related to service discovery but more related to leveraging the native capabilities of a tool. Would it make sense to pull configuration and secrets from K8s ConfigMaps and Secrets instead of the deployed Spring Cloud Config Server?

**Comment by arey** [comment]
@tscrypter thank you for feedback. We are aware of your contribution. A new branch could be great. Or why not a new repository if the are too many changes? I mean we may want to use `Istio` in another branch?

Sure we could replace `Spring Cloud Config Server` by `K8s ConfigMaps`. I found some documentation on the Baeldung's blog: https://www.baeldung.com/spring-cloud-kubernetes

**Comment by sindhams** [comment]
> Hi @sindhams I've never try to deploy the application on kubernetes but I hope someone could help you.



> @sindhams @arey Running this on K8s requires some code and architecture changes. Service Discovery is a feature provided OOTB by K8s.
> 
> Spring Cloud has a Spring-Cloud-Kubernetes project that will support this. Here's a specific link to the [Discovery Client docs](spring-cloud-starter-netflix-eureka-client).
> 
> Also a link to the start of the docs can be found [here](https://cloud.spring.io/spring-cloud-kubernetes/multi/multi__why_do_you_need_spring_cloud_kubernetes.html)
> 
> ### Architecture change:
> 1. K8s provides its own service discovery, so `spring-cloud-discovery-server` won't be deployed.
> 
> ### Code changes:
> 1. Replace `spring-cloud-starter-netflix-eureka-client` with Spring Cloud Kubernetes DiscoveryClient (this is throughout most of the services)
> 2. Fix any issues that arise from the first change (I haven't had a chance to do this on this repo, but for my services in K8s I have services communicating with each other and monitored via SBA using the native Service Discovery)
> 
> I can probably take a stab and creating a PR next week for a new branch in this repo with the updates made to support deployment on K8s, as well as documentation for running a development cluster locally.

thank you @arey . If I can make the services register themselves with Eureka with their IPs (pod IP resolution works in K8s between the pods) , the petclinic app should work in K8s. So I have added the property "perferIpAddress: true" in [discovery-server.yml](url) assuming that the services registration happens with IPs. However services are still registering with pod names , am I missing anything ?

**Comment by tscrypter** [comment]
@arey I'll make the changes in a new branch, and if the changes are significant, I'll leave it to you to create a new repo that I can issue a PR into for spring-petclinic-k8s.

**Comment by arey** [comment]
@arey I propose you submit a PR. Thus I could review your changes and decide with @mszarlinski  if we should create a new repo dedicated to k8s. 
In that case, @tscrypter could you take in charge to report the major evolutions of the repo `spring-petclinic-microservices` to the new one `spring-petclinic-k8s'?

**Comment by tscrypter** [comment]
@arey I can make the changes to evolve `spring-petclinic-microservices` to `spring-petclinic-k8s`.

**Comment by mszarlinski** [comment]
If we want to support k8s under spring-petclinic organization, I would opt for creating a new repository.

**Comment by arey** [comment]
So I've created the `spring-petclinic-kubernetes` repository: https://github.com/spring-petclinic/spring-petclinic-kubernetes
@tscrypter you have the access right and could push to this repo.

**Comment by arey** [comment]
We look at some contributors to run the Spring Petclinic Microservices into K8S
See https://github.com/spring-petclinic/spring-petclinic-kubernetes/issues/2

**Comment by odedia** [comment]
Native Kubernetes support is available in my fork: https://github.com/odedia/spring-petclinic-cloud
