### ISSUE TITLE
JS Content not correctly materialized into API gateway

### ISSUE THREAD

**Issue by ChristianStier** [spring-petclinic/spring-petclinic-microservices#14]
When launching the API gateway via mvn spring-boot:run, the *.js resources are not correctly materialized and delivered, resulting in client-side 404s. When I copied the resources from the UI's target folder into resources/static, they were correctly delivered.

**Comment by mszarlinski** [comment]
It works on [https://github.com/spring-petclinic/spring-petclinic-angular1](Angular branch), so it was broken by refactoring towards microservices .
