### ISSUE TITLE
Failed to fetch https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/index.yaml : 403 Forbidden

### ISSUE THREAD

**Issue by Nilesh61181** [spring-petclinic/spring-petclinic-microservices#144]
I guess the charts are moved, can you update the docker image for these changes

Failed to fetch https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/index.yaml : 403 Forbidden

**Comment by arey** [comment]
Hi @Nilesh61181, do you have the stack trace please ?

**Comment by arey** [comment]
Please reopen this issue if needed.
