### ISSUE TITLE
Tracing With Spring Cloud Sleuth

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-microservices#15]
We could introduce Spring Cloud Sleuth. See https://dzone.com/articles/tracing-in-microservices-with-spring-cloud-sleuth

**Comment by mszarlinski** [comment]
I agree it would be nice to introduce request tracing.

**Comment by arey** [comment]
I could work on it in the next weeks.

**Comment by mszarlinski** [comment]
Enjoy 😊

**Comment by arey** [comment]
When #10 will be merged, we could had some traces to the api gateway module.
