### ISSUE TITLE
Config service gives white label error 

### ISSUE THREAD

**Issue by aditya-malviya** [spring-petclinic/spring-petclinic-microservices#153]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

**Comment by aditya-malviya** [comment]
@trisberg @mklose

**Comment by arey** [comment]
Hi @aditya-malviya. Could you explain us what you need?

**Comment by aditya-malviya** [comment]
> Hi @aditya-malviya. Could you explain us what you need?

I'm unable to run config service

**Comment by arey** [comment]
Once started, could you test the URL: `http://localhost:8888/vets-service-default.yml`

**Comment by aditya-malviya** [comment]
> Once started, could you test the URL: `http://localhost:8888/vets-service-default.yml`

When I run config service in the url why it gives me error?

**Comment by arey** [comment]
Do you have the error message and the stacktrace please?

**Comment by aditya-malviya** [comment]
> Do you have the error message and the stacktrace please?

I get this error on running 

java -jar spring-petclinic-config-server-2.3.1.jar
on localhost:8888


Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Jun 22 19:21:16 IST 2020
There was an unexpected error (type=Not Found, status=404).

**Comment by arey** [comment]
Ok I see: there is no default page nor error page.

**Comment by arey** [comment]
Dos a simple index page like this one could be help you?
![image](https://user-images.githubusercontent.com/838318/85311342-9af43f80-b4b5-11ea-9d93-ca7c7d3fe726.png)

**Comment by aditya-malviya** [comment]
> Dos a simple index page like this one could be help you?
> ![image](https://user-images.githubusercontent.com/838318/85311342-9af43f80-b4b5-11ea-9d93-ca7c7d3fe726.png)

Anything will help, but tell me is this working? I mean if I deploy all the services will this service works?

**Comment by arey** [comment]
This help page has been commited on the `develop` branch. It's just for information. The services are already working.

**Comment by arey** [comment]
Hi @aditya-malviya do you solve your issue?

**Comment by arey** [comment]
Please reopen if needed
