### ISSUE TITLE
Manifest for config-server not found when started with docker-compose

### ISSUE THREAD

**Issue by okkkk-graddda** [spring-petclinic/spring-petclinic-microservices#157]
[root@localhost spring-petclinic-microservices]# docker-compose up
Creating network "spring-petclinic-microservices_default" with the default driver
Pulling config-server (springcommunity/spring-petclinic-config-server:)...
ERROR: manifest for springcommunity/spring-petclinic-config-server:latest not found

**Comment by arey** [comment]
You're right, the `latest`tag does not exist in DockerHub: https://hub.docker.com/r/springcommunity/spring-petclinic-config-server/tags
Could you please build the project with `mvn clean install -P buildDocker`command line or edit the docker-compose file and use the tag `2.1.2`?

**Comment by okkkk-graddda** [comment]
Thank you very much. I made it success with `docker-compose up ` after  `mvn clean install -P buildDocker` for several times until it's successfully built. I guess it turned out  latest not found for failure in build (while not displayed).

> You're right, the `latest`tag does not exist in DockerHub: https://hub.docker.com/r/springcommunity/spring-petclinic-config-server/tags
> Could you please build the project with `mvn clean install -P buildDocker`command line or edit the docker-compose file and use the tag `2.1.2`?
