### ISSUE TITLE
Non-resolvable parent pom

### ISSUE THREAD

**Issue by shivaraman83** [spring-petclinic/spring-petclinic-microservices#159]
Receive this error -  Non-resolvable parent POM for org.springframework.samples.petclinic.admin:spring-petclinic-admin-server:2.3.2: Failure to find org.springframework.samples:spring-petclinic-microservices:pom:2.3.2 

When trying to build.

**Comment by arey** [comment]
Could you please update your repo and rebuild this project?

**Comment by shivaraman83** [comment]
Works fine. Thank you.
