### ISSUE TITLE
How to bring up PetClinic microservices along with UI

### ISSUE THREAD

**Issue by sidharthasubudhi** [spring-petclinic/spring-petclinic-microservices#163]
Hi,
I am new to the forum. I am using PetClinic application for showing testing capability in API and UI automation.
So I need to install the entire package (both MicroServices and UI). Need guidance for this installation.

~Sidhartha

**Comment by arey** [comment]
Hi @sidharthasubudhi. This project provides both UI and REST API. The [`README.md`](https://github.com/spring-petclinic/spring-petclinic-microservices/blob/master/README.md) explains how to build then launch the project.

**Comment by arey** [comment]
Sure you may ask some questions there.

**Comment by sidharthasubudhi** [comment]
Thank you.
1. What are the supporting services (Config and Discovery Server) that must be started before any other application (Customers, Vets, Visits and API).
2. How to start **../mvnw spring-boot:run** command. Please provide more details about this.
3. Is it possible to start UI in any port other than 8080? if so how to do that? (Because Jenkins is running in its default port 8080).
4. I was going though [README.md](https://github.com/spring-petclinic/spring-petclinic-microservices/blob/master/README.md) but I need details about the above questions to start with.

**Comment by arey** [comment]
1. You should start first the config server, second the discovery server, then all other microservices
2. To execute maven, you have to install the JDK 8
3. To change the port number, you have to edit the file https://github.com/spring-petclinic/spring-petclinic-microservices/blob/master/spring-petclinic-api-gateway/src/main/resources/application.yml and add follow this tuto: https://www.baeldung.com/spring-boot-change-port

**Comment by sidharthasubudhi** [comment]
1. I see the following packages are good to work with
spring-petclinic-admin-server
spring-petclinic-config-server
spring-petclinic-discovery-server
But other packages like
spring-petclinic-api-gateway, spring-petclinic-customers-service, spring-petclinic-vets-service, spring-petclinic-visits-service have some compliation errors. 
2.  I executed spring-petclinic-config-server  and then spring-petclinic-discovery-server packages as Maven Test. 
Here I see **server.port: 8888** in .yml files under resources folder.
The execution is successful but when I login **http://localhost:8888**, nothing runs here.
Also I didn't find anywhere port 8080 is defined.
3. I executed spring-petclinic-admin-server and spring-petclinic-api-gateway packages also.
4. All these 4 packages executed as maven test successfully. But when I open **http://localhost:8888** , nothing opens.
Please let me know if I am doing anything wrong and how can I execute them successfully.

**Comment by arey** [comment]
@sidharthasubudhi do you solve your issue?

**Comment by arey** [comment]
Without feedback, I'm closing this issue. Please free to reopen it.
