### ISSUE TITLE
Decouple controller from repository

### ISSUE THREAD

**Issue by pedsf1968** [spring-petclinic/spring-petclinic-microservices#166]
It's better to decouple Controller from repository using Service class.

For each rest API Controller call Service and Service call Repository.

Controller work with DTO and repository with Entities
Service transform Entities in DTOs and DTOs to Entities

Assign to me for my first contribution

**Comment by arey** [comment]
In micro-services architecture, with less code, we don't need to use a classical layer architecture, I mean Controller -> Service -> Repository.
In an older version of Petclinic, it was the case and that has been changed by this commit: https://github.com/spring-projects/spring-petclinic/commit/83ff9a50e378529993f4f772457dd24791b46438
