### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by pedsf1968** [spring-petclinic/spring-petclinic-microservices#167]
Never work on Master branch (production)

Create develop branch for origin to merge other features.

Create Realease to backup differents projets states

Create first RELEASE-1.0.0 for this working Master

**Comment by arey** [comment]
In the community, the `master` is going to be replaced by the `main` branches: https://dev.to/damcosset/replacing-master-in-git-2jim
I think we could wait what GitHub will propose to automate this renaming.

**Comment by arey** [comment]
A first step : I've created a `main` branch for the configuration repository: https://github.com/spring-petclinic/spring-petclinic-microservices-config

**Comment by arey** [comment]
```
The default branch has been renamed!
master is now named main

If you have a local clone, you can update it by running the following commands.

git branch -m master main
git fetch origin
git branch -u main main
git remote set-head origin -a
```
