### ISSUE TITLE
Enable Hystrix Dashboard and Turbine

### ISSUE THREAD

**Issue by mszarlinski** [spring-petclinic/spring-petclinic-microservices#17]
We could configure Hystrix Dashboard and Turbine as described here https://github.com/spring-cloud-samples/hystrix-dashboard

**Comment by mszarlinski** [comment]
I can handle it

**Comment by mszarlinski** [comment]
In progress

**Comment by arey** [comment]
@mszarlinski a part of this issue has been implemented by the PR https://github.com/spring-petclinic/spring-petclinic-microservices/issues/17
But what about Turbine?

**Comment by arey** [comment]
Bad news, we still have to replace them: #117
