### ISSUE TITLE
Add Spring Boot Chaos Monkey

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-petclinic/spring-petclinic-microservices#174]
By adding the Spring Boot Chaos Monkey (https://codecentric.github.io/chaos-monkey-spring-boot/) we could introduce faults and latency that we could then use to demo failure scenarios using Micrometer and Sleuth.

**Comment by arey** [comment]
It's a great. Do you want to contribute to this sample by adding Spring Boot Chaos Monkey ?

**Comment by marcingrzejszczak** [comment]
Sorry I've missed this... Sure, I'll be happy to add it
