### ISSUE TITLE
Consider rewriting one of the business apps to WebFlux

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-petclinic/spring-petclinic-microservices#175]
If one of the business applications was using WebFlux, then we would have all possible combinations of applications (reactive and non reactive). That way we could test whether all of our Spring Cloud libraries work well within those two application types.

**Comment by arey** [comment]
Hi @marcingrzejszczak. Thanks for your proposition. The `spring-petclinic-api-gateway` is already using String Webflux through the `spring-cloud-starter-gateway` starter. Look at the `ApiGatewayController`.

**Comment by marcingrzejszczak** [comment]
Cool!
