### ISSUE TITLE
Add database observability

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-petclinic/spring-petclinic-microservices#176]
Projects to consider:

Tracing - https://github.com/openzipkin/brave/tree/master/instrumentation/p6spy
Tracing & Metrics - https://github.com/gavlyukovskiy/spring-boot-data-source-decorator

**Comment by MarianConstantinMarica** [comment]
Can I work on this issue?

**Comment by marcingrzejszczak** [comment]
Look at this then 

- https://github.com/jdbc-observations/datasource-micrometer
- https://micrometer.io/docs/observation
- https://micrometer.io/docs/tracing

**Comment by arey** [comment]
Of course @MarianConstantinMarica you could work on this new feature. Spring ecosystem observability is now based on micrometer thus we should consider the `datasource-micrometer` project @marcingrzejszczak has referenced.

**Comment by arey** [comment]
The `datasource-micrometer-spring-boot` has been added
