### ISSUE TITLE
Starting services locally with docker-compose failed on Windows 10

### ISSUE THREAD

**Issue by valsaraj** [spring-petclinic/spring-petclinic-microservices#183]
When executed the below command error comes:
mvnw clean install -P buildDocker

[INFO] Reactor Summary:
[INFO]
[INFO] spring-petclinic-microservices 2.4.5 ............... SUCCESS [  0.364 s]
[INFO] spring-petclinic-admin-server ...................... FAILURE [ 29.504 s]
[INFO] spring-petclinic-customers-service ................. SKIPPED
[INFO] spring-petclinic-vets-service ...................... SKIPPED
[INFO] spring-petclinic-visits-service .................... SKIPPED
[INFO] spring-petclinic-config-server ..................... SKIPPED
[INFO] spring-petclinic-discovery-server .................. SKIPPED
[INFO] spring-petclinic-api-gateway 2.4.5 ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.629 s
[INFO] Finished at: 2021-07-13T09:26:28+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:1.2.0:build (default) on project spring-petclinic-admin-server: Exception caught: Head https://registry-1.docker.io/v2/library/openjdk/manifests/11-jre: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fopenjdk%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers) -> [Help 1]

Docker for Windows is used (Expose daemon on tcp://localhost:2375 without TLS)
![image](https://user-images.githubusercontent.com/15048035/125388247-ce558500-e3bc-11eb-91af-e785147936bb.png)

**Comment by arey** [comment]
Hi @valsaraj  Did you solve your issue?
Maybe may we migrate to a more recent plugin or to Buildpacks. Spofity recommends to switch to the [dockerfile-maven ](https://github.com/spotify/dockerfile-maven)

**Comment by timwildberger** [comment]
I have the same issue. @arey, do you have any recommendations on how to solve this problem?

My error is similar:
discovery-server   | Error: Could not find or load main class org.springframework.boot.loader.JarLauncher
discovery-server   | Caused by: java.lang.ClassNotFoundException: org.springframework.boot.loader.JarLauncher
discovery-server   | 2021/07/27 11:30:57 Command exited with error: exit status 1
discovery-server exited with code 1

**Comment by arey** [comment]
I'm sorry. I'm developing on MacOS and thus I cannot reproduce your issue.
Which version of Docker are you using?
And does the command `docker pull hello-world` is working?

**Comment by ramazansakin** [comment]
Hi @valsaraj ,

I had the same issue first but after some research I found that just you need to do is:
On Docker-Desktop/Setings/General

Tick this value : Expose daemon on tcp://localhost:2375 without TLS

**Comment by ramazansakin** [comment]
Hi @arey ,

Like these general problem for all OSs, can you make a like Frequently Occurred Problems section on Readme.
Because if this works for @valsaraj , this issue may be closed soon after that and this disappeared and if another one still
occurs this issue , he/she create a new ticket again and again :) 
Thanks

**Comment by arey** [comment]
Hi @ramazansakin thank you for having found a solution to this issue.
I'm OK to add a FAQ to the `readme.md`. Could you please take it in charge and submit a PR?

**Comment by ramazansakin** [comment]
Ok, sure but lets see if it works for @valsaraj and maybe also for Mac :)

**Comment by valsaraj** [comment]
@ramazansakin I tickes it already as per the screenshot in the ticket description. Unfortunately that didn't worked.
It worked for me when I switched to another faster network connection. So there is something related to that with Docker in my Windows 10 machine. I took latest Docker update but still have problem on that network connection but works fine on another faster network.
 @arey FYI
Thank you all for checking on this.

**Comment by ramazansakin** [comment]
Hi again after a long time :) ,

I think @valsaraj has another problem as I understand and what about you @timwildberger , could you solve the problem ?
Again I checked the "mvn clean install -P buildDocker" command and gets error without the tick of "Expose daemon on tcp://localhost:2375 without TLS" after ticking that it run again and produced all the images.

**Comment by arey** [comment]
Hi @valsaraj Do you find a solution?

**Comment by valsaraj** [comment]
> Hi @valsaraj Do you find a solution?

@arey https://github.com/spring-petclinic/spring-petclinic-microservices/issues/183#issuecomment-930021600
As I mentioned here, it resolved when I switched to faster network. The error I faced was due to timeout. After changing network, docker run worked fine.
