### ISSUE TITLE
Error response from daemon: manifest for springcommunity/spring-petclinic-admin-server:latest not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by donhuvy** [spring-petclinic/spring-petclinic-microservices#190]
```
Microsoft Windows [Version 10.0.22000.318]
(c) Microsoft Corporation. All rights reserved.

D:\github\spring-petclinic-microservices>docker-compose up
[+] Running 0/8
 - customers-service Error                                                                                        20.2s
 - vets-service Error                                                                                             20.2s
 - discovery-server Error                                                                                         20.2s
 - config-server Error                                                                                            20.2s
 - api-gateway Error                                                                                              20.2s
 - admin-server Error                                                                                             20.2s
 - visits-service Error                                                                                           20.2s
 - tracing-server Error                                                                                           20.2s
Error response from daemon: manifest for springcommunity/spring-petclinic-admin-server:latest not found: manifest unknown: manifest unknown

D:\github\spring-petclinic-microservices>
```

![image](https://user-images.githubusercontent.com/1328316/143883256-5d5e386a-dd49-4845-b427-3629945feae4.png)

Please guide me how to fix?

**Comment by arey** [comment]
Hi, the `latest` tag does not exist on Docker Hub: https://hub.docker.com/repository/docker/springcommunity/spring-petclinic-admin-server
Could you try to build the Docker image on your local machine?

**Comment by arey** [comment]
It should be ok now @donhuvy I've published all Docker images with the tags `latest` and `2.5.1`.
Could you please retry?

**Comment by donhuvy** [comment]
@arey Thank you for your attention. It works now. 

It is my log https://gist.github.com/donhuvy/4a6769189b42c9ca52329bb2356af4f7 . Due I am using same port, therefore has port conflict, but I it is the cause from my side. 

Have a nice day!

**Comment by arey** [comment]
The application use the `8080` port and it should not already be used. Let me know.

**Comment by donhuvy** [comment]
Yes. After I turn off many other running web-app, it works.

**Comment by donhuvy** [comment]
@arey , Please also fix on branch `release/java11`

**Comment by arey** [comment]
The `Dockerfile` is now based on java11: https://github.com/spring-petclinic/spring-petclinic-microservices/blob/master/docker/Dockerfile
The `release/java11` branch and the `readme.md` have to be delete / update.

**Comment by arey** [comment]
Please reopen if needed
