### ISSUE TITLE
Remove the release/java11 branch

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-microservices#197]
The Dockerfile is now based on java11: https://github.com/spring-petclinic/spring-petclinic-microservices/blob/master/docker/Dockerfile
The release/java11 branch and the readme.md have to be delete / update.
See the issue https://github.com/spring-petclinic/spring-petclinic-microservices/issues/190

**Comment by charboubmustapha** [comment]
it make sens to move to Java 11 as default JVM and probably another release branch with Java 17

**Comment by arey** [comment]
Spring Boot 3 supports Java as a baseline so we have to remove the release/java11 branch.

**Comment by arey** [comment]
Deleted this day
