### ISSUE TITLE
Starting services with docker-compose

### ISSUE THREAD

**Issue by mszarlinski** [spring-petclinic/spring-petclinic-microservices#2]
We should be able to start all services using Docker following this [example](http://www.kennybastani.com/2015/07/spring-cloud-docker-microservices.html). Before _dockerization_ services can be started locally as described in README.

**Comment by mszarlinski** [comment]
I have found an interesting article about Spring Cloud _dockerization_: http://ryanjbaxter.com/2015/12/15/building-cloud-native-applications-with-spring-part-8/ 
This approach requires creating a dedicated `docker` profile. What do you think? @arey @dsyer

**Comment by dsyer** [comment]
I hate docker. If there's a way to make it optional, please do. Also @ryanjbaxter works for pivotal now so he might have an opinion that we could ask about.

**Comment by ryanjbaxter** [comment]
I am not familiar with this example, but I imagine it would be possible.  I a special docker profile because I often find that you need some different config when running everything in a docker env.  For example the location of the Eureka server.

**Comment by mszarlinski** [comment]
In progress
