### ISSUE TITLE
what is the valor of this variable CONFIG_SERVER_URL

### ISSUE THREAD

**Issue by Spiritbe4r** [spring-petclinic/spring-petclinic-microservices#203]
please a need some help for this .

**Comment by arey** [comment]
Hi @Spiritbe4r. The answer depends the location you deploy the configuration server.
If you run the app on your local desktop, you can reach it at the URL `http://localhost:8888/`

**Comment by arey** [comment]
Please reopen if needed

**Comment by arey** [comment]
For question, we could now use the Discussions tab: https://github.com/spring-petclinic/spring-petclinic-microservices/discussions
