### ISSUE TITLE
Getting Excetption while Building docker Image for whole project

### ISSUE THREAD

**Issue by kbat312** [spring-petclinic/spring-petclinic-microservices#210]
Failed to execute goal com.spotify:docker-maven-plugin:1.2.2:build (default) on project spring-petclinic-admin-server: Exceptio
n caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: com.spotify.docker
.client.shaded.org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1
] failed: Connection refused: connect -> [Help `1]```

**Comment by arey** [comment]
Hi @kbat312 Did you start the Docker Daemon before executing the maven command?

**Comment by arey** [comment]
Please reopen if needed.
