### ISSUE TITLE
Please upgrade to contemporary versions: Spring Boot 3.0.0 and Spring Cloud 2022.0.0-RC2

### ISSUE THREAD

**Issue by donhuvy** [spring-petclinic/spring-petclinic-microservices#216]
Please upgrade to contemporary versions: Spring Boot 3.0.0 and Spring Cloud 2022.x (event RC version). (Edited)

**Comment by arey** [comment]
I'm a not sure that Spring Cloud 2021.0.5 is compatible with Spring Boot 3
See https://docs.spring.io/spring-cloud/docs/current/reference/html/
```
Release Train Version: 2021.0.5
Supported Boot Version: 2.6.13
```
I've created the https://github.com/spring-petclinic/spring-petclinic-microservices/issues/217 for SB 3 et Spring Cloud 2022 migration

**Comment by donhuvy** [comment]
Spring Boot 3.0.0 work with Spring Cloud 2022.0.5-RC2 (it is official information). In about middle of December 2022, Spring Boot 3.x will work with Spring Cloud 2022.x GA (General Availability). Let's see https://stackoverflow.com/questions/74684908/spring-boot-3-0-0-spring-cloud-2021-0-5-no-feign-client-for-loadbalancing-defi#comment131854924_74684908 Comment from Spring team member ([Olga Maciaszek](https://stackoverflow.com/users/2531402/olgamaciaszek))

**Comment by arey** [comment]
Ok so we need Spring Could 2022.
Few months ago, I've started the migration in a working branch: https://github.com/arey/spring-petclinic-microservices/commits/feature/spring-cloud-2022.0
Spring Cloud and Spring Boot was milestones. I have to continue. Or maybe you want to try?

**Comment by donhuvy** [comment]
It is quite hard with me, but I will try. We will try it.

**Comment by arey** [comment]
@donhuvy I'm working on the migration (see https://github.com/arey/spring-petclinic-microservices/commits/feature/spring-cloud-2022.0)
I saw that Spring Cloud Sleuth has to be migrated to Micrometer Tracing.

**Comment by arey** [comment]
I close this issue that duplicates https://github.com/spring-petclinic/spring-petclinic-microservices/issues/217

**Comment by arey** [comment]
See https://github.com/spring-petclinic/spring-petclinic-microservices/pull/221
