### ISSUE TITLE
Remove dockerize

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-microservices#219]
This enhancement has been discussed in the PR https://github.com/spring-petclinic/spring-petclinic-microservices/pull/215
The `docker-compose.yml` could use the `service_started` and/or the `service_healthy` condition.
Like in k8s, the Spring Boot application may have started but is not ready to accept HTTP request.
According to the compose spec, the `service_healthy` looks like better: https://github.com/compose-spec/compose-spec/blob/master/spec.md#healthcheck It requires that we implement healthcheck.
I found this sample: https://github.com/wpcfan/spring-boot-tut/blob/master/docker/docker-compose.yml

**Comment by alexandre-touret** [comment]
Hi
Dont you think, it could also be an opportunity to use the springboot docker plugin instead of the Spotify one?

e.g.:
```bash
./mvnw spring-boot:build-image 
```

**Comment by arey** [comment]
@alexandre-touret We're on our way. See https://github.com/spring-petclinic/spring-petclinic-microservices/pull/247
