### ISSUE TITLE
Making switching easier between github and local repository

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-microservices#22]
Today, we have to comment/uncomment few lines in spring-petclinic-config-server/src/main/resources/application.yml :
```
git:
          uri: https://github.com/spring-petclinic/spring-petclinic-microservices-config
          # Uncomment for local configuration repository:
          # uri: file:///${GIT_REPO}
```
Spring Cloud Config Server provides advanced features like environment repository. Maybe could we use it?
https://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_environment_repository

**Comment by mszarlinski** [comment]
It is definitely the right way to do this.
