### ISSUE TITLE
getting 500 

### ISSUE THREAD

**Issue by danishcool77** [spring-petclinic/spring-petclinic-microservices#224]
1 service not able to communicate with another service

even though eureka server  dashboard shows all 4 services up & running 
getting this :

java.net.UnknownHostException: Failed to resolve 'MOHADANI-7410.in.oracle.com' after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1069)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 

this is  my host file:

127.0.0.1 peer1
#100.76.138.152 backup-server
127.0.0.1 peer2
#127.0.0.1 auth-server
#127.0.0.1 config
#127.0.0.1 registry
#127.0.0.1 auth-service
#127.0.0.1 rabbitmq
#127.0.0.1 CN=wls-sysadm
#10.40.73.56 whf00gbb.in.oracle.com
127.0.0.1 whf00gbb.in.oracle.com
#127.0.0.1 localhost

**Comment by arey** [comment]
Hi @danishcool77 did you try by using the `localhost`?

**Comment by arey** [comment]
Please reopen if your issue is not solved
