### ISSUE TITLE
How to deploy this project on a K8S cluster?

### ISSUE THREAD

**Issue by CSHH1122** [spring-petclinic/spring-petclinic-microservices#226]
I tried to deploy the project on a K8S cluster but encountered some issues.May I ask if anyone can provide a K8S deployment file?

**Comment by arey** [comment]
Hi @CSHH1122 The https://github.com/spring-petclinic/spring-petclinic-cloud is a 
fork of the Spring Cloud Microservices project packaged to be deployed on several Cloud platforms: Kubernetes and Cloud Foundry

**Comment by CSHH1122** [comment]
Thank you so much!!!

**Comment by arey** [comment]
You're welcome :)
