### ISSUE TITLE
Regression: avoid download dockerize-alpine-linux-amd64-v0.6.1.tar.gz

### ISSUE THREAD

**Issue by Stefan-5422** [spring-petclinic/spring-petclinic-microservices#227]
Looking through issues and merged PRs it seems this has already been fixed once, although it still seems to be an issue:
Issue #136 was fixed by #148
> each time build images by executing ./mvnw clean install -PbuildDocker ,it needs download dockerize-alpine-linux-amd64-v0.6.1.tar.gz from github, can you do some optimization?

**Comment by arey** [comment]
It looks like the fix is not working or have been breaked.
Does someone has any idea to cache dockerize?

**Comment by arey** [comment]
Should be fixed by https://github.com/spring-petclinic/spring-petclinic-microservices/pull/247
