### ISSUE TITLE
Connection to MySql DB

### ISSUE THREAD

**Issue by amrutha2234** [spring-petclinic/spring-petclinic-microservices#231]
While checking I'm not able view the configuration file for DB connections, to change to my own DB, could you please help out. 
@arey 
Thanks

**Comment by arey** [comment]
Hi @amrutha2234 
Did you follow the readme instructions? https://github.com/spring-petclinic/spring-petclinic-microservices#database-configuration
At what step are you blocked?

**Comment by amrutha2234** [comment]
Hi @arey ,
Sorry for late reply, I did read the readme file, I'm a bit confused where the DB endpoint is given.
![image](https://github.com/spring-petclinic/spring-petclinic-microservices/assets/135020148/73f92237-5056-4096-a349-7c885d8f9d5e)

While connecting to services via EKS I'm not able to connect to DB, I'm starting out to use Kubernetes, this is my college project, please help out.
Thank you for your time and cooperation.

**Comment by arey** [comment]
You have to look at the `mysql` profile of the application configuration file that is hosted into another repository: https://github.com/spring-petclinic/spring-petclinic-microservices-config/blob/main/application.yml#L76

**Comment by amrutha2234** [comment]
Hi @arey,
Thank you so much for helping me.
