### ISSUE TITLE
The "RPS" generated by locust is much fewer 

### ISSUE THREAD

**Issue by odidev** [spring-petclinic/spring-petclinic-microservices#236]
@arey, I performed load testing on a HTTP interface with locust and found that the 'RPS' generated by locust is very less. 

Details of load testing: 
1. 6 locust worker nodes
2. 160 users, RPS=44.1 
3. Spawn rate =16

![1 petclininc](https://github.com/spring-petclinic/spring-petclinic-microservices/assets/40816837/74559541-e15e-4a56-b207-d3735730da33) 
![10 petclinic](https://github.com/spring-petclinic/spring-petclinic-microservices/assets/40816837/7ddb213d-2337-4316-8c65-c42dc55ae95b)
![6 petclinic](https://github.com/spring-petclinic/spring-petclinic-microservices/assets/40816837/9cf63f71-be2a-442e-9c81-2caf20a16232)

The `api/customer/owners`, `api/customer/owners/pets` and `api/customer/pettypes` APIs are taking more time to response for the given requests (get and post) while load testing using locust. As the average response time for the APIs is greater than expected, it shows decreased RPS.   

Above `160 users` the RPS value decreases and it shows failures. 

Could you please share some pointers for the same? Let me know if you need any other information.

**Comment by odidev** [comment]
@arey, could you please share your  feedback regarding the above issue.

**Comment by arey** [comment]
Hi @odidev 

The  `docker-compose up` command line starts all the microservices on the same machine. I don't think this is a good practice for scalability testing. his means you can't take advantage of the horizontal scalability provided by a microservices architecture.

The 3 microservices `vets-service`, `visits-service` and `customers-service` could have replicas. You could increase `customers-service`  replica number to 2 or 3. To do this you don't have to use in memory database but a `MySQL` or `PostgreSQL` database that could share their data between instances.

**Comment by odidev** [comment]
Hi [@arey](https://github.com/arey) , 

As per your suggestion, I have added the replicas for the 3 microservices `vets-service`, `visits-service` and `customers-service` in the docker-compose.yml file which is mentioned below:

[docker-compose.yml](https://github.com/spring-petclinic/spring-petclinic-microservices/files/12105491/docker-compose.1.txt)

If I add replicas to `vets-services` and `visits-services` it does not show any change in RPS and failures, but after adding the replicas to `customers-service` it shows increase in RPS, but the failures are increased for a smaller number of users. 

Previously, it was supporting upto 160 users after adding replicas it is not able to support 100 users. I also tested for 50 users, but it still shows 3 to 5 failures. 

Logs of load testing for 160 users after adding replicas: 
[result of 160 users](https://github.com/spring-petclinic/spring-petclinic-microservices/files/12105546/report_1689842796.568641.pdf)

**Comment by odidev** [comment]
[@arey](https://github.com/arey), could you please share your feedback regarding the above issue.

**Comment by seungmin-uplus** [comment]
@odidev, Could you share the locust.py? I am testing Observability services using spring-petclinic service, and looking for loadtesting service to create enough traffic.

**Comment by arey** [comment]
Thank you @odidev for your new test.

In order to identify the source of the errors, I'll need the logs. Did you keep them?

At the same time, although it's practical on the dev station, I'm not sure that `docker-compose` is the best tool to deploy a microservice architecture in a live environment. All microservices are deployed on the same machine. There is a risk of CPU overload.

**Comment by arey** [comment]
I'll close this question. To continue our discussion, we could use the https://github.com/spring-petclinic/spring-petclinic-microservices/discussions feature
