### ISSUE TITLE
Active Health Check with Spring Cloud Gateway

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-microservices#237]
Active health check will check and drop unhealthy services in the background before receiving the request. It doesn't add extra latency.

See https://spring.io/blog/2023/07/05/active-health-check-strategies-with-spring-cloud-gateway

**Comment by MarianConstantinMarica** [comment]
Can I work on this?

**Comment by arey** [comment]
Yes @MarianConstantinMarica you're welcome

**Comment by arey** [comment]
As far as the official documentation is concerned, this idea is not appropriate.
https://docs.spring.io/spring-cloud-commons/reference/spring-cloud-commons/loadbalancer.html

> Tip: This mechanism is particularly helpful while using the SimpleDiscoveryClient. For the clients backed by an actual Service Registry, it’s not necessary to use, as we already get healthy instances after querying the external ServiceDiscovery.

> Tip: This supplier is also recommended for setups with a small number of instances per service in order to avoid retrying calls on a failing instance.

> Warning: If using any of the Service Discovery-backed suppliers, adding this health-check mechanism is usually not necessary, as we retrieve the health state of the instances directly from the Service Registry.
