### ISSUE TITLE
Upgrade to Spring Cloud 2023.0

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-microservices#240]
* Spring Cloud 2023.0.0-M1 (aka Leyton) has been released: https://spring.io/blog/2023/08/10/spring-cloud-2023-0-0-m1-aka-leyton-has-been-released
* Spring Cloud 2023.0.0-M2 (aka Leyton) has been released: https://spring.io/blog/2023/09/29/spring-cloud-2023-0-0-m2-aka-leyton-has-been-released
* Spring Cloud 2023.0.0 (aka Leyton) Is Now Available : https://spring.io/blog/2023/12/06/spring-cloud-2023-0-0-aka-leyton-is-now-available

**Comment by shobhakamath** [comment]
@arey  Can I take this task?

**Comment by arey** [comment]
Yes you can

**Comment by arey** [comment]
Done trough https://github.com/spring-petclinic/spring-petclinic-microservices/pull/249
