### ISSUE TITLE
changing default database configuration

### ISSUE THREAD

**Issue by nibarAhmed** [spring-petclinic/spring-petclinic-microservices#256]
hello. Can you help clear up where i can change the default database configuration for spring-petclinic before i build my images? I'm going to deploy this on a cloud provider for testing and i need to have MySQL set as default for my images rather than running it via profiles. Preferable would be to know how i change my db configuration, which files and where to put them before building as specified by the dockumentation.

**Comment by arey** [comment]
Hi @nibarAhmed did you follow the documentation https://github.com/spring-petclinic/spring-petclinic-microservices?tab=readme-ov-file#use-the-spring-mysql-profile
