### ISSUE TITLE
Add Spring Boot Admin

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-microservices#27]
Console to manage and monitor our micro-services Spring Boot Applications.
See https://github.com/codecentric/spring-boot-admin and https://spring.io/blog/2016/12/07/spring-tips-bootiful-dashboards

**Comment by arey** [comment]
If you are interested, I coud work on it next week.

**Comment by arey** [comment]
An overview of what is comming:
![admin-server](https://cloud.githubusercontent.com/assets/838318/21744218/b6c7283a-d511-11e6-9219-cb4fc8a8f8da.png)

**Comment by mszarlinski** [comment]
Nice, excited 👍
