### ISSUE TITLE
I have created yaml files with images which is created by givin cmd.but in the gate way data is not loaded .

### ISSUE THREAD

**Issue by ASLAM467** [spring-petclinic/spring-petclinic-microservices#277]
I have created yaml files with images which is created by givin cmd.but in the gate way data is not loaded .

**Comment by arey** [comment]
Hi @ASLAM467 to help you we required some additional informations: command lines, logs, yaml content ...

**Comment by ASLAM467** [comment]
Can you  plz provide all yaml files link ...I need to register data through
the api gateway and data should be submitted.

**Comment by arey** [comment]
Hi @ASLAM467 Your question seems to be outside the scope of this project. Please reopen if not.
