### ISSUE TITLE
Genai Chatbot startup failure

### ISSUE THREAD

**Issue by colljos** [spring-petclinic/spring-petclinic-microservices#282]
Followed instructions as per [Integrating the Spring AI Chatbot](https://github.com/odedia/spring-petclinic-microservices/?tab=readme-ov-file#integrating-the-spring-ai-chatbot) but application fails to start-up with following error:

```
***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 2 of method openAiEmbeddingModel in org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration required a bean of type 'org.springframework.web.client.RestClient$Builder' that could not be found.
Action:
Consider defining a bean of type 'org.springframework.web.client.RestClient$Builder' in your configuration.
```

I have attempted to follow the advice in https://github.com/spring-projects/spring-ai/issues/563  and associated https://github.com/spring-projects/spring-ai/issues/524 but issue continues.

**Comment by colljos** [comment]
Just realised this codebase in not yet merged into the main branch:
https://github.com/spring-petclinic/spring-petclinic-microservices/pull/281

@odedia can you comment on the error I am seeing? 
NB: I am using the Open AI starter: _spring-ai-openai-spring-boot-starter_ (not the Azure default).

**Comment by arey** [comment]
Hi @colljos
If you want test it, I've just merged the genai branch into the main branch of the spring petclinic microservices service.
