### ISSUE TITLE
Can't start up to run properly

### ISSUE THREAD

**Issue by Dovchiproeng** [spring-petclinic/spring-petclinic-microservices#46]
I build the image and run it using docker-compose up. However, first the Eureka server run without any service register and then after that the server is down and I am getting this message.

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
here is the docker container status, it shows that vet service and discover server is down
`$ docker ps -a
CONTAINER ID        IMAGE                                            COMMAND                  CREATED             STATUS                           PORTS                              NAMES
b8162318af40        mszarlinski/spring-petclinic-api-gateway         "./wait-for-it.sh ..."   About an hour ago   Up 11 minutes                    0.0.0.0:8080->8080/tcp, 8081/tcp   api-gateway
68cea08a482a        mszarlinski/spring-petclinic-admin-server        "./wait-for-it.sh ..."   About an hour ago   Up 11 minutes                    0.0.0.0:9090->9090/tcp             admin-server
07c26aebd421        mszarlinski/spring-petclinic-visits-service      "./wait-for-it.sh ..."   About an hour ago   Up 11 minutes                    8081/tcp, 0.0.0.0:8082->8082/tcp   visits-service
f324acabf068        mszarlinski/spring-petclinic-customers-service   "./wait-for-it.sh ..."   About an hour ago   Up 11 minutes                    0.0.0.0:8081->8081/tcp             customers-service
f932e13278e1        mszarlinski/spring-petclinic-tracing-server      "./wait-for-it.sh ..."   About an hour ago   Up 11 minutes                    8081/tcp, 0.0.0.0:9411->9411/tcp   tracing-server
f05b0a543745        mszarlinski/spring-petclinic-vets-service        "./wait-for-it.sh ..."   About an hour ago   Exited (137) 8 minutes ago                                          vets-service
3bad154db2f5        mszarlinski/spring-petclinic-discovery-server    "./wait-for-it.sh ..."   About an hour ago   Exited (137) 9 minutes ago                                          discovery-server
dae366586bd2        mszarlinski/spring-petclinic-config-server       "java -Djava.secur..."   About an hour ago   Up 11 minutes                    0.0.0.0:8888->8888/tcp             config-server
f896bb4fa245        mszarlinski/spring-petclinic-config-server       "java -Djava.secur..."   About an hour ago   Exited (143) About an hour ago                                      serene_ramanujan
71d25de9280d        mszarlinski/spring-petclinic-config-server       "java -Djava.secur..."   About an hour ago   Exited (143) About an hour ago                                      pensive_fermi
87c3ba3928ad        mszarlinski/spring-petclinic-config-server       "java -Djava.secur..."   About an hour ago   Exited (143) About an hour ago                                      loving_pasteur`

**Comment by mszarlinski** [comment]
Please wait for all services to register in Eureka. You can track a progress of registration on Eureka dashboard available at `http://localhost:8761`. Once `api-gateway` is registered, you can access application UI at `8080`.

**Comment by Dovchiproeng** [comment]
Yes I read it in the readme file too, but the problem is now the Eureka server is down after it start and so all the service can't be registered.

**Comment by mszarlinski** [comment]
I am unable to reproduce this issue. It might be related to your local environment, like insufficient memory available for containers. 

Could you please try to run apps manually, without docker-compose or Docker at all?

**Comment by Dovchiproeng** [comment]
Thanks for your suggestion, I found out the issue is because of the Memory of my docker engine. I increase it from 2GB to 6GB. It works fine now!
