### ISSUE TITLE
Memory issue while running in AWS

### ISSUE THREAD

**Issue by renuraj18** [spring-petclinic/spring-petclinic-microservices#49]
I am facing memory issue while running the microservice in AWS.
Is the any Tuned Java options available?

**Comment by mszarlinski** [comment]
Hi, @renuraj18. I guess nobody has tried to run the app on AWS as of yet. However, you can adjust JVM settings in a regular way.

**Comment by renuraj18** [comment]
Thanks for the update.
Closing this issue.
