### ISSUE TITLE
On windows the owner details do not show up

### ISSUE THREAD

**Issue by birdy81** [spring-petclinic/spring-petclinic-microservices#51]
Hi, I faced the problem that the owner details did not show up when I run the pet clinic on windows. Strangely, running on ubuntu there was no problem. After I changed the file "/spring-petclinic-api-gateway/src/main/resources/static/scripts/owner-details/owner-details.controller.js"
and changed rest call: "api/gateway/owners/" to "api/customer/owners/" everything was working again. Have you faced the problem to?

**Comment by arey** [comment]
@mszarlinski I'm working on MacOS and I don't have this problem.

**Comment by mszarlinski** [comment]
1. Using `api/customer/owners` you get owners without visits related to their pets. Please see 
[ApiGatewayController#getOwnerDetails](https://github.com/spring-petclinic/spring-petclinic-microservices/blob/master/spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/boundary/web/ApiGatewayController.java#L45), where additional fetching of visits occurs.
In real life scenario, this endpoint could be concealed from the frontend and accessed only via edge server (Zuul).
2. @arey no problems on Windows neither. @birdy81 do you use docker-compose or manual startup? Maybe you forget to start `visits-service`?

**Comment by birdy81** [comment]
Hi, thank you for your quick reply. I used a different fork of the petClinic and started it without docker-compose using my own startupscript that just calls the mvn run command. The problem must be there.  With your master branch it is also working on windows. Sorry for the inconvenience! And thank you for the work on this application!
