### ISSUE TITLE
Forward error with proxy

### ISSUE THREAD

**Issue by renuraj18** [spring-petclinic/spring-petclinic-microservices#54]
Hi,

I am facing issue with the proxy, its throwing forward error. Its not resolving with container id

api-gateway       | 2017-04-11 06:07:03.355  WARN [api-gateway,cf2a4d11d8028d75,cf2a4d11d8028d75,true] 1 --- [nio-8080-exec-5] o.s.c.n.z.filters.post.SendErrorFilter   : Error during filtering
api-gateway       |
api-gateway       | com.netflix.zuul.exception.ZuulException: Forwarding error
api-gateway       |     at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.handleException(RibbonRoutingFilter.java:170)
api-gateway       |     at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:145)
api-gateway       |     at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:88)
api-gateway       |     at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112)

++

api-gateway       |     at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:139)
api-gateway       |     ... 70 common frames omitted
api-gateway       | Caused by: java.lang.RuntimeException: java.net.UnknownHostException: f7937d25199b: Name or service not known
api-gateway       |     at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
api-gateway       |     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
api-gateway       |     at rx.observables.BlockingObservable.single(BlockingObservable.java:342)
api-gateway       |     at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:102)
api-gateway       |     ... 133 common frames omitted
api-gateway       | Caused by: java.net.UnknownHostException: f7937d25199b: Name or service not known
api-gateway       |     at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)

**Comment by arey** [comment]
Do you find a solution to your issue?

**Comment by arey** [comment]
Any news
