### ISSUE TITLE
Config Server image not found on DockerHub

### ISSUE THREAD

**Issue by kmcquade** [spring-petclinic/spring-petclinic-microservices#57]
Getting this error when I run _docker-compose up_ 

ERROR: repository mszarlinski/spring-petclinic-config-server not found: does not exist or no pull access

Looked at [the profile on DockerHub](https://hub.docker.com/u/mszarlinski/) and it appears that the Docker repo is not there. 

Suggestions?

**Comment by mszarlinski** [comment]
Hi @kmcquade, I apologise but images have not been pushed yet. I will work on it. You can still build your own images using maven plugin - just run `mvn clean install -PbuildDocker` as pointed in README.

**Comment by kmcquade** [comment]
Yep, figured that out a little while after I posted this issue. I had to modify the docker-compose.yml file to reference the Dockerfiles within each project folder. I ran the `mvn clean install -PbuildDocker` command for each of those folders, and only ran into issues with one of them. This one was for the customers-service project:

`[ERROR] Failed to execute goal on project spring-petclinic-customers-service: Could not resolve dependencies for project org.springframework.samples.petclinic.client:spring-petclinic-customers-service:jar:1.5.3: Failed to collect dependencies at org.springframework.samples.petclinic.monitoring:spring-petclinic-monitoring:jar:1.5.3: Failed to read artifact descriptor for org.springframework.samples.petclinic.monitoring:spring-petclinic-monitoring:jar:1.5.3: Failure to find org.springframework.samples:spring-petclinic-microservices:pom:1.5.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`

Suggestions?

Thanks for your response. Excited to get this working.

**Comment by mszarlinski** [comment]
Try running `mvn clean install -PbuildDocker` on root directory, it should build all required images - "it works on my machine" :)

**Comment by kmcquade** [comment]
Figured out the issue... I didn't have Oracle JDK installed in my VM (it was running on JRE). Guess I didn't have to modify the docker-compose.yml file to reference the local Dockerfiles, etc. I also didn't have to run the maven command in all the projects... tried that as a workaround initially but of course the missing JDK in my VM was the issue.

Thanks for your help. Glad it's working now! Issue closed.
