### ISSUE TITLE
hsqldb only imports Cusomers

### ISSUE THREAD

**Issue by arnelism** [spring-petclinic/spring-petclinic-microservices#58]
When running customers service, only Customers table is populated with data. Pet Types and Pets remain empty. Bug/feature/keyboardDriverError?

**Comment by arey** [comment]
According to the data.sql file of the spring-petclinic-customer-service, 3 tables has to be populated: owners, pets and types.

**Comment by arey** [comment]
According to the data.sql file of the spring-petclinic-customer-service, 3 tables has to be populated: owners, pets and types.

**Comment by arey** [comment]
According to the data.sql file of the spring-petclinic-customer-service, 3 tables has to be populated: owners, pets and types.

**Comment by arey** [comment]
Any feedback
