### ISSUE TITLE
Running the evict task with compensationTime 0ms

### ISSUE THREAD

**Issue by sachrekar21** [spring-petclinic/spring-petclinic-microservices#60]
Hi,

While deploying the containers on AWS, i get the following output and it just keeps on going in a loop and not progressing further:
![error](https://user-images.githubusercontent.com/29106184/27706800-f4555f8a-5ce0-11e7-81c0-5bd99ae1455d.png)
Can you please help me out with this issue?

**Comment by mszarlinski** [comment]
Hi, we don't support AWS as of yet. Any help appreciated.

**Comment by sachrekar21** [comment]
Hi,

Thanks for getting back. One of my colleague also tried it on his local MAC. Still have the same error.

Shreyas Achrekar

Sent from my Samsung mobile

**Comment by mszarlinski** [comment]
Please provide a stacktrace and elaborate how you start services.
