### ISSUE TITLE
data-access.properties file is missing

### ISSUE THREAD

**Issue by ambrish24** [spring-petclinic/spring-petclinic-microservices#62]
In the **petclinic_db_setup_mysql.txt file**, it has been mentioned that for MySQL configuration we need to do the changes in **data-access.properties** file. I didn't find this file in this repository.

In **spring-petclinic/spring-petclinic-microservices-config repository**, I can provide MySQL configuration for these services' .yml files like

1. customers-service.yml
2. vets-service.yml and
3. visits-service.yml

Is there any other way so that I can place **data-access.properties** file at one place in  **spring-petclinic/spring-petclinic-microservices-config** repository and it will be picked by all 3 services?

**Comment by ambrish24** [comment]
I have given the MySQL configuration in **spring-petclinic/spring-petclinic-microservices-config** repository's **application.yml**.

Closing the issue.

**Comment by mszarlinski** [comment]
I will look into it next week, Thanks for PR
