### ISSUE TITLE
Docker Images - Missing

### ISSUE THREAD

**Issue by jwlai** [spring-petclinic/spring-petclinic-microservices#63]
Hi, 

I was trying to launch this in docker and ran into these Image Repository links to be empty. Is there a reason they were taken down?

Thanks.

"mszarlinski/spring-petclinic-admin-server" and all other images.

**Comment by mszarlinski** [comment]
I have pulled images, please try again.

**Comment by jwlai** [comment]
Awesome, thank you @mszarlinski !
