### ISSUE TITLE
MySQL switch documentation

### ISSUE THREAD

**Issue by mikessun** [spring-petclinic/spring-petclinic-microservices#65]
In petclinic_db_setup_mysql.txt, following file was mentioned but the file does not exist in the repo:
src/main/resources/spring/data-access.properties

**Comment by mszarlinski** [comment]
Thanks for pointing out, I will fix it.

**Comment by SyCode7** [comment]
@mszarlinski  any update on this, I could not switch to MYSQL because of this .

**Comment by mszarlinski** [comment]
We are open to contribution, it is open source :)

**Comment by arey** [comment]
I'm working to improve the documentation

**Comment by SyCode7** [comment]
@arey thank you so much 😀
