### ISSUE TITLE
Client modules naming

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-microservices#7]
The names of those 2 maven modules are confused: 
* spring-petclinic-client  => front-end 
* spring-petclinic-clients-service => Owner and Pet

We could rename the spring-petclinic-clients-service into spring-petclinic-customers-service (and the java package too). What do you think ?

**Comment by mszarlinski** [comment]
Good point, I suggest `spring-petclinic-ui` and `spring-petclinic-customers-service`.

**Comment by arey** [comment]
I like it.
