### ISSUE TITLE
changing base java image

### ISSUE THREAD

**Issue by SyCode7** [spring-petclinic/spring-petclinic-microservices#75]
I am trying to change the base java image to `openjdk:8-jre-alpine`, please how can this be done ?
Update: I have found where to effect this change, I tried changing in the vets microservice however it returns an error at build time : 
 ` ---> Running in 2bbecdd578b6
/bin/sh: bash: not found`

**Comment by arey** [comment]
@SyCode7 do you solve your issue?

**Comment by SyCode7** [comment]
@arey no, still have it.

**Comment by arey** [comment]
It looks like Alpine Linux image doesn't contain bash, Instead you can use /bin/ash, /bin/sh, ash or only sh or install it: apk --update bash

**Comment by arey** [comment]
The base java image has been changed to openjdk:8-jre-alpine in the recent commit: https://github.com/spring-petclinic/spring-petclinic-microservices/commit/318c08ae8b7e68e41a21791a5f6243f7b1075f0f thanks to @Xaseron
