### ISSUE TITLE
Add OpenAPI (Swagger) support 

### ISSUE THREAD

**Issue by SyCode7** [spring-petclinic/spring-petclinic-microservices#79]
Due to the rising support for OpenAPI (swagger), it will be nice to add OpenAPI support for PetClinic microservices. I have  done this in a forked [version](https://github.com/SyCode7/spring-petclinic-microservices-swagger). For example, for the  Vets service, the  VisitsServiceApplication class will be as [here](spring-petclinic-microservices-swagger/spring-petclinic-visits-service/src/main/java/org/springframework/samples/petclinic/visits/VisitsServiceApplication.java) . Similarly, the pom files have to include the requirred dependencies as shown [here](spring-petclinic-microservices-swagger/spring-petclinic-vets-service/pom.xml). In my case, I have leveraged [SpringFox API](http://springfox.github.io/springfox/). I can create a pull request if you want.

**Comment by arey** [comment]
Thank you @SyCode7 for your suggestion.
I'm note sure this Petclinic fork is the right place for an OpenAPI integration. There still a lot of technology to integrate.
Why not in the spring-petclinic-rest fork or in a branch? @mszarlinski @vfedoriv any idea?

**Comment by vfedoriv** [comment]
Already implemented in spring-petclinic-rest fork.
Still some problems with migration to Spring Boot 2
https://github.com/springfox/springfox/issues/1773

**Comment by arey** [comment]
@SyCode7 you may help @vfedoriv and the community to improve the https://github.com/spring-petclinic/spring-petclinic-rest fork

**Comment by SyCode7** [comment]
@arey sure, I gonna take a look and provide some support. Please you may close this issue if okay. Thanks.

**Comment by arey** [comment]
Thanks a lot @SyCode7
