### ISSUE TITLE
mvn clean install -PbuildDocker don't work

### ISSUE THREAD

**Issue by donydex** [spring-petclinic/spring-petclinic-microservices#81]
It is my error info:

> Step 9/10 : EXPOSE ${EXPOSED_PORT}
                                                                                                      │[INFO] ------------------------------------------------------------------------
                                                                                                      │[INFO] Reactor Summary:
                                                                                                      │[INFO] 
                                                                                                      │[INFO] spring-petclinic-microservices ..................... SUCCESS [  0.246 s]
                                                                                                      │[INFO] spring-petclinic-admin-server ...................... FAILURE [ 10.753 s]
                                                                                                      │[INFO] spring-petclinic-monitoring ........................ SKIPPED
                                                                                                      │[INFO] spring-petclinic-customers-service ................. SKIPPED
                                                                                                      │[INFO] spring-petclinic-vets-service ...................... SKIPPED
                                                                                                      │[INFO] spring-petclinic-visits-service .................... SKIPPED
                                                                                                      │[INFO] spring-petclinic-config-server ..................... SKIPPED
                                                                                                      │[INFO] spring-petclinic-discovery-server .................. SKIPPED
                                                                                                      │[INFO] spring-petclinic-api-gateway ....................... SKIPPED
                                                                                                      │[INFO] spring-petclinic-tracing-server .................... SKIPPED
                                                                                                      │[INFO] ------------------------------------------------------------------------
                                                                                                      │[INFO] BUILD FAILURE
                                                                                                      │[INFO] ------------------------------------------------------------------------
                                                                                                      │[INFO] Total time: 11.951 s
                                                                                                      │[INFO] Finished at: 2018-07-11T10:30:27+08:00
                                                                                                      │[INFO] Final Memory: 75M/651M
                                                                                                      │[INFO] ------------------------------------------------------------------------
                                                                                                      │[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (default) on project spri
                                                                                                      │ng-petclinic-admin-server: Exception caught: EXPOSE requires at least one argument -> [Help 1]
                                                                                                      │[ERROR] 
                                                                                                      │[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
                                                                                                      │[ERROR] Re-run Maven using the -X switch to enable full debug logging.
                                                                                                      │[ERROR] 
                                                                                                      │[ERROR] For more information about the errors and possible solutions, please read the following artic
                                                                                                      │les:
                                                                                                      │[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
                                                                                                      │[ERROR] 
                                                                                                      │[ERROR] After correcting the problems, you can resume the build with the command
                                                                                                      │[ERROR]   mvn <goals> -rf :spring-petclinic-admin-server

It seems like the expose require an argument.What it should be?

This is the dockerfile:
![image](https://user-images.githubusercontent.com/11333398/42547827-9db295e6-84f6-11e8-9ab9-1c229df8b4ca.png)
I have tried to set EXPOSE_PORT to 22 and 8899 which doesn't work.
This error info:

> [ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (default) on project spri
                                                                                                      │ng-petclinic-admin-server: Exception caught: Request error: POST unix://localhost:80/build?buildargs=
                                                                                                      │%7B%22ARTIFACT_NAME%22%3A%22spring-petclinic-admin-server-1.5.9%22%2C%22EXPOSED_PORT%22%3A%229090%22%
                                                                                                      │7D&t=mszarlinski/spring-petclinic-admin-server: 500: HTTP 500 Internal Server Error -> [Help 1]
                                                                                                      │[ERROR] 

Thanks!

**Comment by arey** [comment]
Did you run the Docker daemon?

**Comment by donydex** [comment]
Yes,I have
![image](https://user-images.githubusercontent.com/11333398/42607980-340303d4-85b8-11e8-8781-b3bfe58e6255.png)
This is my question in stackoverflow.
https://stackoverflow.com/questions/51277418/mvn-clean-install-pbuilddocker-dont-work
Thanks!Wait for your answer!

**Comment by arey** [comment]
I've create the #82 to upgrade the Docker maven plugin but the current one is working on my macbook and Docker 18.05.0-ce-rc.

**Comment by arey** [comment]
There is already an issue about builder Docker image with Maven: #64
Do you have checked the answers?

**Comment by arey** [comment]
No feedback. Please reopen this issue if your problem persists.
