### ISSUE TITLE
spring-petclinic-customer-service

### ISSUE THREAD

**Issue by Pophalekiran** [spring-petclinic/spring-petclinic-microservices#84]
I took the latest code from git. I tried to compile the spring-petclinic-customer-service but it was failing for dependency "spring-petclinic-monitoring:jar:2.0.3". I tried to solve it but nothing worked for me.
Can you please suggest

**Comment by Pophalekiran** [comment]
Hi there,

I did the build it from root path but when I was trying to run spring-petclinic-customer-service and I was facing below error, I tried to use mvn install command in spring-petclinic-monotoring project but no use,

[ERROR] Failed to execute goal on project spring-petclinic-customers-service: Could not resolve dependencies for project org.springframework.samples.petclinic.client:spring-petclinic-customers-service:jar:2
.0.3: Failed to collect dependencies at org.springframework.samples.petclinic.monitoring:spring-petclinic-monitoring:jar:2.0.3: Failed to read artifact descriptor for org.springframework.samples.petclinic.m
onitoring:spring-petclinic-monitoring:jar:2.0.3: Failure to find org.springframework.samples:spring-petclinic-microservices:pom:2.0.3 in http://repo.spring.io/milestone was cached in the local repository, r
esolution will not be reattempted until the update interval of repository.spring.milestone has elapsed or updates are forced -> [Help 1]

**Comment by arey** [comment]
Could you please try to go to the spring-petclinic-monitoring sub-directory and you manualy build the org.springframework.samples.petclinic.monitoring:spring-petclinic-monitoring:jar:2.0.3 artefact?

**Comment by arey** [comment]
Any news?

**Comment by arey** [comment]
No feedback. Please reopen this issue if your problem persists.
