### ISSUE TITLE
Removal of the spring-petclinic-monitoring module

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-microservices#89]
@mszarlinski, in order to simplify the base code, I suggest to remove the spring-petclinic-monitoring Maven module shared by all the microservices. Monitoring metrics are now sent to Zipkin trough distributed traces. What do you think about?

**Comment by mszarlinski** [comment]
👍 it is some legacy stuff

**Comment by arey** [comment]
Ok I take this change.
