### ISSUE TITLE
How to spit the spring-petclinic-microservices into different machines?

### ISSUE THREAD

**Issue by donydex** [spring-petclinic/spring-petclinic-microservices#90]
Right now the application is run in just one machine.
How can i split the microservices into different machines?
Thanks.

**Comment by mszarlinski** [comment]
Hi, thank you for your comment. Application is split already into separate services that can be run independently manually as well as using Docker containers, on premise or in cloud. If you want to run apps on different machines, you should take care of all the networking configuration by yourself or use advanced tool like Kubernetes.
