### ISSUE TITLE
EnableAdminServer cannot be resolved to a type

### ISSUE THREAD

**Issue by JavaHelper** [spring-petclinic/spring-petclinic-microservices#93]
I am getting below error..

![image](https://user-images.githubusercontent.com/8208031/45920602-2ba68180-bec4-11e8-8e25-798c7a8380c4.png)

**Comment by mszarlinski** [comment]
Hi, it is difficult to figure out what the problem is only from attached screenshot. Does Maven build your code? What is the error message shown in Eclipse?

**Comment by arey** [comment]
Any news @JavaHelper?

**Comment by arey** [comment]
No feedback. Please reopen this issue if your problem persists.
